python3 SFT_codesearch.py \
    --output_dir=./ \
    --train_data_file_CodeSearch=./datasets/code_search/train.jsonl \
    --eval_data_file_CodeSearch=./datasets/code_search/valid.jsonl\
    --test_data_file_CodeSearch=./datasets/code_search/test.jsonl \
    --model_name_or_path=deepseek-ai/deepseek-coder-1.3b-base \
    --tokenizer_name=deepseek-ai/deepseek-coder-1.3b-base \
    --nl_length 128 \
    --code_length 256 \
    --do_train \
    --train_batch_size 8 \
    --eval_batch_size 8 \
    --train_data_rate_code_search 1.0 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 10 \
    --seed 42 2>&1 | tee ./logs_deepseek/codeSearch_lora.log
